### ISSUE TITLE
clicking on a torrent link in Vivaldi does not send to Download Master

### ISSUE THREAD

**Issue by zany130** [acc15/asus-downloader-chrome#4]
So on Vivaldi (which is based on chromium) clicking on a link doesn't send it to download master. I have to right-click and click on the send option. Is this intentional or is something not working right?

**Comment by acc15** [comment]
Read Usage - its intentional. You must have an option to download torrent manually.

Usage
Right-click on any link and select 'Download with ASUS Download Master'. Torrent files are auto-detected so you don't need to worry about this. You will see notification about success or error.
